name: Continuous Integration Build

on:
   push:
      branches: [ main, feature/* ]
   # pull_request:
   #    branches: [ main ]
   # workflow_dispatch: { }

jobs:
   build:
      name: 'Build, Test, and Publish'
      runs-on: ubuntu-latest

      steps:
         -  name: Check out
            uses: actions/checkout@v5
            with:
               fetch-depth: 0

         -  name: Acquire .NET SDK
            uses: actions/setup-dotnet@v5
            with:
               dotnet-version: '9.0.x'
               cache: false
               source-url: ${{ vars.YUMA_AZURE_FEED_URL }}
            env:
               NUGET_AUTH_TOKEN: ${{ secrets.YUMA_AZURE_FEED_API_KEY }}

         -  name: Restore .NET tools
            run: dotnet tool restore

         -  name: Run CI NUKE Build
            run: >
               dotnet nuke --target CI --configuration Release
               --AzureFeedApiKey ${{ secrets.YUMA_AZURE_FEED_API_KEY }}
               --AzureFeedUrl ${{ vars.YUMA_AZURE_FEED_URL }}
               --NuGetApiKey ${{ secrets.YUMA_NUGET_FEED_API_KEY }}
               --NuGetUrl ${{ vars.YUMA_NUGET_FEED_URL }}

         -  name: Upload code coverage and mutation test reports
            if: always()
            uses: actions/upload-artifact@v4
            with:
               name: html-test-reports
               path: artifacts/reports/*.html
               if-no-files-found: warn
               retention-days: 30

         -  name: Upload NuGet packages
            if: always()
            uses: actions/upload-artifact@v4
            with:
               name: nuget-packages
               path: |
                  artifacts/nuget/*.nupkg
                  artifacts/nuget/*.snupkg
               if-no-files-found: error
               retention-days: 30
